name: Java Security & Quality Scan

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: Build and run tests
        run: mvn clean verify -B

      # ----------- SONARCLOUD -----------
      - name: SonarCloud Scan
        run: |
          mvn sonar:sonar \
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \
            -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION }} \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.login=${{ secrets.SONAR_TOKEN }}

      # ---------- CACHE OWASP DEPENDENCY CHECK ----------
      - name: Cache OWASP dependency data
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository/org/owasp/dependency-check-data
          key: owasp-nvd-${{ runner.os }}

      # ---------- OWASP DEPENDENCY CHECK ----------
      - name: Run OWASP Dependency Check
        env:
          NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        run: |
          mvn org.owasp:dependency-check-maven:check \
            -Dnvd.api.key=${{ secrets.NVD_API_KEY }} \
            -Dnvd.api.validforhours=24 \
            -Dnvd.api.delay=500 \
            -DfailBuildOnCVSS=11 \
            -Dformats=HTML,XML \
            -DoutputDirectory=dependency-check-report \
            -Danalyzer.nvd.api.waitTime=2000 \
            -Danalyzer.nvd.api.timeout=30000

      # ---------- SNYK SCAN (optional, dacă ai cont) ----------
        #- name: Snyk Scan
        #uses: snyk/actions/maven@master
          #with:
        #args: test
          #env:
        #SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # ---------- ARTEFACTE RAPOARTE ----------
      - name: Upload dependency-check report
        uses: actions/upload-artifact@v4
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html